GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/200

###
DELETE http://localhost:3001/api/persons/2
###
POST  http://localhost:3001/api/notes/
Content-Type: application/json

{"content":"HTML is easy bal bal","important":true}

